### ISSUE TITLE
Query related to training

### ISSUE THREAD

**Issue by Rukhmini** [taozh2017/HiNet#12]
Hello,
Is it possible to train the network with the data provided in the data folder or do we need to download the whole dataset? I am facing an error while training the network with the dataset given in the data folder. The error is given below:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    fire.Fire()
  File "C:\Users\rukhm\Anaconda3\envs\gpu_env\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\rukhm\Anaconda3\envs\gpu_env\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\rukhm\Anaconda3\envs\gpu_env\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 20, in train
    SynModel.train() 
  File "C:\Users\rukhm\HiNet-master\HiNet_SynthModel.py", line 99, in train
    for ii, inputs in enumerate(train_loader):
  File "C:\Users\rukhm\Anaconda3\envs\gpu_env\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\rukhm\Anaconda3\envs\gpu_env\lib\site-packages\torch\utils\data\dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\rukhm\Anaconda3\envs\gpu_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\rukhm\Anaconda3\envs\gpu_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\rukhm\HiNet-master\dataset.py", line 66, in __getitem__
    img_t1,img_t1ce,img_t2,img_flair = loadSubjectData(cur_path)
  File "C:\Users\rukhm\HiNet-master\dataset.py", line 28, in loadSubjectData
    img_t1    = img_t1[40:200,20:200,:]
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

**Comment by taozh2017** [comment]
You need to download the whole dataset. Can you try to tune one step by step to fix the error?

**Comment by 2805413893** [comment]
Hello, I have the same problem, is the above error caused by incomplete dataset, also would like to get your matlab code for converting the .nii format file to .mat format file in the dataset, thank you very much for your answer and code provision.My email is 2085413893@qq.com

**Comment by 2805413893** [comment]
Hello, I have the same problem, is the above error caused by an incomplete dataset? Also would like to get your matlab code for converting the .nii format files in the dataset to .mat format files, thank you very much for your answer and code availability. My Email is 2805413893@qq.com.

**Comment by zzmm711** [comment]
您好，我最近在调试这一代码，数据集好像是不完整的，对于完整数据集的转换存在一些疑问，请问可以参考一下您的matlab代码吗？非常感谢！我的邮箱是1449047983@qq.com。

**Comment by taozh2017** [comment]
> 您好，我最近在调试这一代码，数据集好像是不完整的，对于完整数据集的转换存在一些疑问，请问可以参考一下您的matlab代码吗？非常感谢！我的邮箱是[1449047983@qq.com](mailto:1449047983@qq.com)。

你需要.nii转换成.mat的code？我马上整理好发给你

**Comment by taozh2017** [comment]
> Hello, I have the same problem, is the above error caused by an incomplete dataset? Also would like to get your matlab code for converting the .nii format files in the dataset to .mat format files, thank you very much for your answer and code availability. My Email is [2805413893@qq.com](mailto:2805413893@qq.com).

ok. I will sort it and then send it to you.

**Comment by zzmm711** [comment]
好的，非常谢谢您！



---Original---
From: "Tao ***@***.***&gt;
Date: Thu, Aug 12, 2021 11:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [taozh2017/HiNet] Query related to training (#12)




  
***@***.***。
  
你需要.nii转换成.mat的code？我马上整理好发给你
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzmm711** [comment]
您好，可以麻烦您把.nii转换成.matde code发我一下吗？



---Original---
From: "Tao ***@***.***&gt;
Date: Thu, Aug 12, 2021 11:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [taozh2017/HiNet] Query related to training (#12)




  
***@***.***。
  
你需要.nii转换成.mat的code？我马上整理好发给你
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by taozh2017** [comment]
> 您好，我最近在调试这一代码，数据集好像是不完整的，对于完整数据集的转换存在一些疑问，请问可以参考一下您的matlab代码吗？非常感谢！我的邮箱是[1449047983@qq.com](mailto:1449047983@qq.com)。

已发。

**Comment by Rukhmini** [comment]
Can you also send me the code for conversion? My email id is rukhmini.roy788@gmail.com. Thank you!
